# NumPy Exercises

<a id='import_required_libraries'></a>
## Import required libraries
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [1]:
# importing the core library
import numpy as np

<a id='1'></a>
### *Exercise 1*. Import numpy as np and see the version
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [3]:

import numpy as np
print(np.__version__)

1.24.4


<a id='2'></a>
### *Exercise 2*. How to create a 1D array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [4]:
# Question : Create a 1D array of numbers from 0 to 9
# Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a id='3'></a>
### *Exercise 3*. How to create a boolean array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [5]:
# Question : Create a 3×3 numpy array of all True’s

# Solution
np.full((3,3), True, dtype=bool)

#or
np.full((9), True, dtype=bool).reshape(3,3)

#or
np.ones((3,3), dtype=bool)

#or
np.ones((9), dtype=bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

<a id='4'></a>
### *Exercise 4*. How to extract items that satisfy a given condition from 1D array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [6]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

#Solution

arr = np.arange(10)

arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

<a id='5'></a>
### *Exercise 5*. How to replace items that satisfy a condition with another value in numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [7]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Solution

arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

<a id='6'></a>
### *Exercise 6*. How to replace items that satisfy a condition without affecting the original array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [31]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution

arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1



In [35]:
out


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a id='7'></a>
### *Exercise 7*. How to reshape an array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [37]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])

# Solution

arr = np.arange(10)
arr.reshape(2,5)

# Another solution
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<a id='8'></a>
### *Exercise 8*. How to stack two arrays vertically?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [10]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

# Solution

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<a id='9'></a>
### *Exercise 9*. How to stack two arrays horizontally?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [11]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


# Solution:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

<a id='10'></a>
### *Exercise 10*. How to get the common items between two python numpy arrays?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [13]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])


# Solution:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

<a id='12'></a>
### *Exercise 12*. How to remove from one array those items that exist in another?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [14]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])


# Solution
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

<a id='14'></a>
### *Exercise 14*. How to extract all numbers between a given range from a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [16]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)


# Solution

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

<a id='16'></a>
### *Exercise 16*. How to swap two columns in a 2d numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [38]:
# Question: Swap columns 1 and 2 in the array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
arr



Original array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
# Solution

print("\nModified array")
arr[:, [1,0,2]]



Modified array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

<a id='17'></a>
### *Exercise 17*. How to swap two rows in a 2d numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [40]:
# Question: Swap rows 1 and 2 in the array arr:

# Input: 

arr = np.arange(9).reshape(3,3)
print('Original array')
arr



Original array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
# Solution

print("\nModified array")
arr[[1,0,2], :]


Modified array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

<a id='18'></a>
### *Exercise 18*. How to reverse the rows of a 2D array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [42]:
# Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
arr



Original array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
# Solution

print("\nModified array")
arr[::-1, :]


Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

<a id='19'></a>
### *Exercise 19*. How to reverse the columns of a 2D array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [21]:
# Question: Reverse the columns of a 2D array arr.

# Input: arr = np.arange(9).reshape(3,3)

# Solution

arr = np.arange(9).reshape(3,3)
print('Original array')
arr


print("\nModified array")
arr[:, ::-1]

Original array

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

<a id='20'></a>
### *Exercise 20*. How to create a 2D array containing random floats between 5 and 10?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [22]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:

rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[5.16732487, 5.53022715, 5.78143508],
       [7.10625164, 8.79823114, 7.9810214 ],
       [8.10325313, 6.00839459, 9.95669267],
       [6.06001105, 6.7997641 , 8.4955287 ],
       [8.48158574, 7.8246262 , 8.20915957]])

<a id='21'></a>
### *Exercise 21*. How to print only 3 decimal places in python numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [23]:
# Question: Print or show only 3 decimal places of the numpy array rand_arr.

# Input: rand_arr = np.random.random((5,3))

rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.986, 0.84 , 0.55 ],
       [0.041, 0.525, 0.734],
       [0.818, 0.389, 0.454],
       [0.551, 0.047, 0.946],
       [0.37 , 0.86 , 0.197]])

<a id='22'></a>
### *Exercise 22*. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [1]:
1/1e3

0.001

In [24]:
# Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input: 
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
rand_arr

# Output:
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

np.set_printoptions(suppress=True)
rand_arr
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

<a id='23'></a>
### *Exercise 23*. How to limit the number of items printed in output of numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [25]:
# Question: Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

<a id='24'></a>
### *Exercise 24*. How to print the full numpy array without truncating
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [26]:
# Question: Print the full numpy array a without truncating.

# Input: np.set_printoptions(threshold=6)
# a = np.arange(15)
# a

# Output: a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution

a = np.arange(15)


np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<a id='25'></a>
### *Exercise 25*. How to import a dataset with numbers and texts keeping the text intact in python numpy?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [51]:
# Question: Import the iris dataset keeping the text intact.

# Solution:
iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', skip_header=1, 
                          usecols = [0,1,2,3,4], dtype = object)
iris_data

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'setosa'],
       [b'4.9', b'3', b'1.4', b'0.2', b'setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'setosa'],
       ...,
       [b'6.5', b'3', b'5.2', b'2', b'virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'virginica'],
       [b'5.9', b'3', b'5.1', b'1.8', b'virginica']], dtype=object)

The b prefix in the output you're seeing (b'5.1', b'3.5', etc.) indicates that the data you're reading is being interpreted as bytes rather than strings. This typically happens when NumPy reads the file as raw byte data 

<a id='26'></a>
### *Exercise 26*. How to extract a particular column from 1D array of tuples?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [52]:
# Question: Extract the text column species from the 1D iris imported in previous question.

data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', skip_header=1, 
                          usecols = [-1], dtype = object)
data

array([b'setosa', b'setosa', b'setosa', ..., b'virginica', b'virginica',
       b'virginica'], dtype=object)

<a id='27'></a>
### *Exercise 27*. How to convert a 1d array of tuples to a 2d numpy array? 
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [53]:
# Question: Convert the 1D iris to 2D array iris_2d by omitting the species text field.
iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', skip_header=1, dtype='float', usecols=[0,1,2,3])
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

<a id='28'></a>
### *Exercise 28*. How to compute the mean, median, standard deviation of a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [54]:
# Question: Find the mean, median, standard deviation of iris's sepallength (1st column)

iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', skip_header=1, usecols = [1])

print('Mean', np.mean(iris_data))
print('Median', np.median(iris_data))
print('Standard Deviation', np.std(iris_data))

Mean 3.0540000000000003
Median 3.0
Standard Deviation 0.4321465800705435


<a id='29'></a>
### *Exercise 29*. How to normalize an array so the values range exactly between 0 and 1?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [55]:
# Question: Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

# Solution

iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', dtype='float', usecols=[1], skip_header=1)

(iris_data - np.min(iris_data))/(np.max(iris_data) - np.min(iris_data))

array([0.625, 0.417, 0.5  , ..., 0.417, 0.583, 0.417])

<a id='31'></a>
### *Exercise 31*. How to find the percentile scores of a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [57]:
# Question. Find the 5th and 95th percentile of iris's sepallength
iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', dtype='float', usecols=[1], skip_header=1)

np.percentile(iris_data, q=[5, 95])

array([2.345, 3.8  ])

<a id='34'></a>
### *Exercise 34*. How to filter a numpy array based on two or more conditions?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [65]:
# Question: Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', dtype='float', usecols=[1,2,3,4], skip_header=1)

# Solution
iris_data[(iris_data[:, 2] > 1.5) & (iris_data[:, 0] < 5.0)]

array([[3.3, 4.7, 1.6, nan],
       [3.2, 4.8, 1.8, nan],
       [3. , 5. , 1.7, nan],
       ...,
       [3. , 5.2, 2. , nan],
       [3.4, 5.4, 2.3, nan],
       [3. , 5.1, 1.8, nan]])

<a id='35'></a>
### *Exercise 35*. How to drop rows that contain a missing value from a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [67]:
# Question: Select the rows of iris_2d that does not have any nan value.

diabetes_data = np.genfromtxt(r'C:\Users\USER\Downloads\diabetes.csv', delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7], skip_header=1)
diabetes_data[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan #This line introduces missing values (np.nan) at random locations in a 2D array
diabetes_data[np.sum(np.isnan(diabetes_data), axis = 1) == 0][:5]

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  1.   ,  89.   ,  66.   , ...,  28.1  ,   0.167,  21.   ],
       [  0.   , 137.   ,  40.   , ...,  43.1  ,   2.288,  33.   ],
       [  5.   , 116.   ,  74.   , ...,  25.6  ,   0.201,  30.   ]])

<a id='36'></a>
### *Exercise 36*. How to find the correlation between two columns of a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [70]:

#  I am going to used pima diabetes data and going to find corelation between BP(1st column) and BMI (5th column).

diabetes_data = np.genfromtxt(r'C:\Users\USER\Downloads\diabetes.csv',
                              delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7], skip_header=1)

print(np.corrcoef(diabetes_data[:, 1], diabetes_data[:, 5]))



[[1.    0.221]
 [0.221 1.   ]]


<a id='37'></a>
### *Exercise 37*. How to find if a given array has any null values?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [71]:
# question: Find out if iris_2d has any missing values.
diabetes_data = np.genfromtxt(r'C:\Users\USER\Downloads\diabetes.csv',
                              delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7], skip_header=1)

np.isnan(diabetes_data).any()

False

<a id='38'></a>
### *Exercise 38*. How to replace all missing values with 0 in a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [72]:
# Question: Replace all ccurrences of nan with 0 in numpy array

wine_quality = np.genfromtxt(r'C:\Users\USER\Downloads\winequality-red.csv',
                             delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7,8,9,10], skip_header=1)

wine_quality[np.random.randint(len(wine_quality), size=20), np.random.randint(11, size=20)] = np.nan

print("Does dataset have any Nan value:",np.isnan(wine_quality).any())

wine_quality[np.isnan(wine_quality)] = 0

print("Does dataset have any Nan value:",np.isnan(wine_quality).any())

Does dataset have any Nan value: True
Does dataset have any Nan value: False


<a id='41'></a>
### *Exercise 41*. How to create a new column from existing columns of a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [42]:
# Question: Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\iris data.csv', delimiter=',', 
                          dtype=object, usecols=[1,2,3,4], skip_header=1)

sepallength = iris_data[:, 0].astype('float')
petallength = iris_data[:, 2].astype('float')

new_column = (np.pi * petallength * (sepallength**2))/3

new_column = new_column[:, np.newaxis]
#new_column

# Add the new column
out = np.hstack([iris_data, new_column])

# View
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', 38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', 35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', 33.238050274980004]], dtype=object)

<a id='44'></a>
### *Exercise 44*. How to sort a 2D array by a column
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [75]:
# Question: Sort the iris dataset based on sepallength column.
# In this problem, I am going to sort the diabetes dataset based on Glucose (1th column)
diabetes_data = np.genfromtxt(r'C:\Users\USER\Downloads\diabetes.csv',
                              delimiter=',', dtype=object, usecols=[0,1,2,3,4,5,6,7,8], skip_header=1)

diabetes_data[diabetes_data[:,1].argsort()]

array([[b'1', b'0', b'74', ..., b'0.299', b'21', b'0'],
       [b'5', b'0', b'80', ..., b'0.346', b'37', b'1'],
       [b'1', b'0', b'68', ..., b'0.389', b'22', b'0'],
       ...,
       [b'4', b'99', b'72', ..., b'0.294', b'28', b'0'],
       [b'4', b'99', b'76', ..., b'0.223', b'21', b'0'],
       [b'2', b'99', b'60', ..., b'0.453', b'21', b'0']], dtype=object)

<a id='45'></a>
### *Exercise 45*. How to find the most frequent value in a numpy array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [76]:
# Question: Find the most frequent value of petal length (3rd column) in iris dataset.

iris_data = np.genfromtxt(r'C:\Users\USER\Downloads\diabetes.csv', delimiter=',', 
                          dtype=object, usecols=[1,2,3,4,5], skip_header=1)

v,c = np.unique(iris_data[:, 2], return_counts=True)
v[np.argmax(c)]

b'0'

<a id='47'></a>
### *Exercise 47*. How to replace all values greater than a given value to a given cutoff?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [79]:
# Question: From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

# Solution

a = np.random.uniform(1,50, 20)
a


array([24.785, 48.368, 11.356, 21.171, 49.494,  2.392, 35.365,  2.233,
       16.723,  4.603,  3.983,  6.459,  9.294, 31.757, 22.481, 41.714,
       12.75 , 10.313, 35.883, 43.056])

In [80]:
a[a<10]=10
a[a>30]=30
np.set_printoptions(threshold=20)
a

array([24.785, 30.   , 11.356, 21.171, 30.   , 10.   , 30.   , 10.   ,
       16.723, 10.   , 10.   , 10.   , 10.   , 30.   , 22.481, 30.   ,
       12.75 , 10.313, 30.   , 30.   ])

<a id='50'></a>
### *Exercise 50*. How to convert an array of arrays into a flat 1d array?
<a href="#top" class="btn btn-primary btn-sm" role="button" aria-pressed="true" style="color:white" data-toggle="popover">Go to TOC</a>

In [51]:
# Question: Convert array_of_arrays into a flat linear 1d array.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

arr_2d = np.concatenate([arr1, arr2, arr3])
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]
